version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - laravel-net
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "laravel-test:127.0.0.1"
  vue3-app:
    build:
      context: .       # Set build context to the "docker" folder
      dockerfile: ./docker/vue3/Dockerfile  # Set Dockerfile path to "docker/vue3/Dockerfile"
    container_name: vue3-app    # Set container name to "vue3-app"
    ports:
      - "80:80"                # Map host port 80 to container port 80
    networks:
      - laravel-net

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: laravel-nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel-net
    depends_on:
      - app
      - vue3-app

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
